[package]
name = "catla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.12.0"
regex = "0.1"
llvm-sys = "140.0.2"
anyhow = "1.0"
